### PR TITLE
Wm python3 django2

### PR DESCRIPTION
**Pull request by wrmack**
Hi Ben

Hope I am doing this correctly.

### CODE REVIEW

**Comment by joaomorenorf** [comment]
Hi, I could not upload voters, is celery working correctly?

**Comment by wrmack** [comment]
@joaomorenorf I will check re celery.  I have another branch which is live on Heroku and upload seems to work fine on that: [https://helios-heroku.herokuapp.com](https://helios-heroku.herokuapp.com).

Are you working on merging this?

**Comment by joaomorenorf** [comment]
I'm just reviewing your code. :)
It seems I have to install rabbitmq to get this working.

**Comment by wrmack** [comment]
Yes.

You might like to look at my repository directly rather than Ben’s master:
https://github.com/wrmack/helios-server/tree/wm-python3-django2 <https://github.com/wrmack/helios-server/tree/wm-python3-django2>

I have two branches there.

You could raise any further issues there.

I found Ben’s original documentation a bit sparse for a noobie (which is really what I am) so I tried to develop more comprehensive documentation here:

https://wrmack.github.io/helios-server-docs/site/ <https://wrmack.github.io/helios-server-docs/site/>

It may or may not help you.



Warwick McNaughton

Email:   warwick.mcnaughton@gmail.com
Mobile:  021 191 1009
Skype:  warwick.mcnaughton
Viber:  +6421 191 1009

**Comment by itamarjp** [comment]
@wrmack nice patch, I hope it get merged soon.

I am using heroku and seems a good place to deploy helios.

**Comment by benadida** [comment]
Thank you @wrmack, I went with @McCio's branch as I had to choose one.

**Pull request closed without merging**
