### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by McCio**
As anticipated on #217, this PR includes changes and dependencies upgrades to only support Python 3 (tested with 3.7): Python 2 support is dropped, as it is already out of maintenance.
Django version is kept here at 1.11, a future PR from [McCio/road-to-django3](https://github.com/McCio/helios-server/tree/road-to-django3) will contain its upgrade to version 3.
Main changes:
* some crypto code has been changed to use [pycryptodome](https://github.com/Legrandin/pycryptodome) (see 5bb385dfdecad98b617e67b8d97a9a8b64fc8b7d): discussion on this change is more than welcome
* enforced AUTH_ENABLED_SYSTEMS (see 9e1e2179bd34e8c07aa8f67fe4c54fbeaef82526)
* upgraded `psycopg2`, `django-picklefield`, `python-openid`>`python3-openid`, `unicodecsv`, `boto`, `django-ses`, `oauth2client`, `validate_email`>`py3-validate-email`, `bleach`, `gunicorn`, `rollbar`
* removed `anyjson`, `pyparsing`, `html5lib`, `requests`, `webtest` as unused and removed explicit `kombu` as imported by `celery`
* tests improvements and general cleanup
* `str`/`bytes` challenges
* `2to3` utility changes with manual intervention

### CODE REVIEW

**Comment by adamalexandru4** [comment]
@McCio I didn't cloned this branch, but I cloned your branch "road-to-django3". 
There are some issues with generate new key for trustees. Am I wrong?

**Comment by adamalexandru4** [comment]
I found the issue, it is based on deprecation of jQuery library and methods for getting JSON objects in the key_generator and verify_sk templates. If it's needed I can post the code here.

**Comment by McCio** [comment]
> I found the issue, it is based on deprecation of jQuery library and methods for getting JSON objects in the key_generator and verify_sk templates. If it's needed I can post the code here.

Hey @adamalexandru4, that would be much useful!

**Comment by benadida** [comment]
@McCio I've rebased your PR onto `master`, just a small set of changes, now available in my repo road-to-py3, though I would much prefer if you rebased yours and updated this PR, so we can keep discussing here. I'm going to try to play with this version a bit and see how it fares!

**Comment by McCio** [comment]
@benadida I've merged the new master, no issue from my side.
The jQuery issues mentioned above should appear when updating jQuery, which isn't done in this branch.

**Comment by benadida** [comment]
integrated the commits into master, thank you!

**Pull request closed without merging**
