### PR TITLE
Fix not allowed navigate top frame

### PR DESCRIPTION
**Pull request by shirlei**
@benadida Google Chrome now throws "Not allowed to navigate top frame to data URL:" JavaScript exception when trying to save secret key. So, for security reasons, this is not allowed anymore and maybe other browsers may soon do the same.
Some information here:
https://ourcodeworld.com/articles/read/682/what-does-the-not-allowed-to-navigate-top-frame-to-data-url-javascript-exception-means-in-google-chrome
which links to the discussion in here:
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM%5B1-25%5D
I've tested the changes in Firerox 64.0.2, Chrome Version 71.0.3578.98 and Safari Version 12.0.3.
Instead of opening a new window, a textarea element is shown in the same window with the content.
Since I was doing such changes, I've also put a function to download the trustee key to a file. In terms of UX I think it is not that clear that he/she can save to a file, for instance, and that he/she should keep the key saved. In my institution we had a case where the election manager added a trustee and he/she didn't save the key... luckly, it was a minor one...
So, now it is possible to copy it from a textarea (as was possible before from a top frame data url) and also to download it direct to a file.
Looking forward to hear from you about the changes.
Thanks!

### CODE REVIEW

**Comment by shirlei** [comment]
@benadida this error on continuous integration "ImportError: No module named google_compute_engine" are you aware of? I saw it on your PR as well : https://travis-ci.org/benadida/helios-server/builds/466348841
Locally, installing from scratch from your branch all tests have passed... It seems infrastructure related... some new configuration maybe?

**Comment by benadida** [comment]
this is lovely, thank you @shirlei. Let me figure out the CI problem.

**Comment by benadida** [comment]
ahah https://github.com/travis-ci/travis-ci/issues/7940 -- let's see how to fix this.

**Comment by benadida** [comment]
I have merged #212 into master that adds the workaround in the Travis build. Now to figure out how to retrigger the tests on this PR....

**Comment by benadida** [comment]
this is frustrating, TravisCI is not picking up the new .travis.yml for some reason. I'm going to merge this and take the risk... Given @shirlei I believe the tests will pass on master.

**Comment by benadida** [comment]
and master is green :) all is good!

**Pull request merged**
