### PR TITLE
Import Helios Models After Django Setup

### PR DESCRIPTION
**Pull request by itamarjp**
move the import lines to after django.setup() to avoid the error bellow

### CODE REVIEW

**Comment by itamarjp** [comment]
without these changes the flowing error message appear.

Traceback (most recent call last):
  File "extract-passwords-for-email.py", line 14, in <module>
    from helios.models import Election
  File "/code/helios/models.py", line 27, in <module>
    from helios_auth.models import User, AUTH_SYSTEMS
  File "/code/helios_auth/models.py", line 19, in <module>
    class User(models.Model):
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
s

**Comment by itamarjp** [comment]
Pull-request updated, HEAD is now 96f87098877028ac09054edbe07be1f61e800442

**Comment by itamarjp** [comment]
Pull-request updated, HEAD is now e9f2506035ee86bbf651405241e7863b7517ebb0

**Comment by itamarjp** [comment]
Pull-request updated, HEAD is now e9f2506035ee86bbf651405241e7863b7517ebb0

**Review by benadida — APPROVED** [review]
great!

**Pull request merged**
