### PR TITLE
Delete an election

### PR DESCRIPTION
**Pull request by edmarmartineli**
admin can delete an election (issue #78)

### CODE REVIEW

**Comment by benadida** [comment]
@edmarmartineli this looks good in terms of functionality. I'd like to start having more tests for these new functions. Can you add a test in `helios/tests.py` that creates an election and deletes it successfully, and then ideally try to delete an election that has a vote showing it can't be deleted.

**Comment by edmarmartineli** [comment]
I implemented delete and undelete elections. I need to implement tests related to this.

**Comment by benadida** [comment]
@edmarmartineli looks like an extra migration slipped in which makes your migration conflict. Can you fix that in your PR?

**Comment by edmarmartineli** [comment]
I simplified the exclusion confirmation because many users could not perform the task

**Pull request closed without merging**
