### PR TITLE
Add ldap auth

### PR DESCRIPTION
**Pull request by shirlei**

### CODE REVIEW

**Comment by shirlei** [comment]
Hi! I've started having some travis problems with pull request #100, so I closed it and made a new one. This one is up to date with your latest changes and includes some testing as we discussed in that pull request. Please, let me know what you think. Thank you!

**Comment by shirlei** [comment]
Hi @benadida ! Did you have some time to take a look at this one? Thanks!!

**Comment by benadida** [comment]
@shirlei sorry for the delay, I didn't notice this was updated.

So I'm still worried about hitting a live LDAP server for tests. That means you need to be online for tests to work, which seems like a much worse experience for anyone developing. Is there a way to mock out the LDAP service instead? Maybe using https://pypi.python.org/pypi/mockldap/0.2.6 ?

**Comment by shirlei** [comment]
@benadida much better! I appreciate if you could see the changes and tell me what you think now. Thanks!

**Comment by benadida** [comment]
this looks much better! Merging.

**Pull request merged**
